### PR TITLE
"leaderboard added"

### LINKED ISSUE #2: Preloader frontend part

### PR DESCRIPTION
**Pull request by neeraj15022001**

### CODE REVIEW

**Comment by neeraj15022001** [comment]
Screenshot 2020-10-19 at 2 15 01 AM
@ishandeveloper Checkout some changes in above screenshot

**Review by ishandeveloper — CHANGES_REQUESTED** [review]
Hey @Neeraj3508 . Nice job on the frontend part!

The only thing I'm not able to understand is why're you using Nodejs Server ? You can still make a fetch request using static html and vanilla js. Setting up hosting with a nodejs server is going to somewhat more expensive and slow (for freemium services like heroku). 

Whereas, For hosting static webpages we can do that on Github Pages or Vercel for free.

**Comment by neeraj15022001** [comment]
Oksy i will look into this and make changes accordingly

**Comment by neeraj15022001** [comment]
Screenshot 2020-10-19 at 8 45 34 PM
Final Screenshot

**Review by ishandeveloper — APPROVED** [review]

**Comment by ishandeveloper** [comment]
Fabulous job, @Neeraj3508 ! I'll deploy this soon.

**Comment by neeraj15022001** [comment]
> Fabulous job, @Neeraj3508 ! I'll deploy this soon.

Thanks @ishandeveloper

**Comment by ishandeveloper** [comment]
> 
> 
> > Fabulous job, @Neeraj3508 ! I'll deploy this soon.
> 
> Thanks @ishandeveloper

@Neeraj3508  You can check it out at : https://dsc-ciet-leaderboard.web.app/     : )

**Comment by neeraj15022001** [comment]
> > 
> > 
> > > Fabulous job, @Neeraj3508 ! I'll deploy this soon.
> > 
> > Thanks @ishandeveloper
> 
> @Neeraj3508  You can check it out at : https://dsc-ciet-leaderboard.web.app/     : )

Hey @ishandeveloper  we have some issues top 5 and top 20 are not working in deployed version and also in all last names are cutting out just the first letter ia visible

**Comment by neeraj15022001** [comment]
@ishandeveloper  just change the url for api in top5.js and top20.js of i will fix it and make a pr

**Pull request merged**
